Задание 9го спринта на проверку
PrincSiama/java-filmorate pull request #2
Opened 2023-07-06 08:36 UTC by PrincSiama

2023-07-06 10:43 UTC, mysosnovskaya requested changes

2023-07-06 10:43 UTC, mysosnovskaya commented on pom.xml
> +    <description>Demo project for Spring Boot</description>
Описание лучше изменить или вообще удалить

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate controlReliseDate = LocalDate.of(1895, 12, 28);
для объявления констант используются модификаторы private final static, а для именования самих констант используются заглавные буквы, разделенные нижним подчеркиванием там, где нужны пробелы (CONTROL_RELISE_DATE)

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate controlReliseDate = LocalDate.of(1895, 12, 28);
А ещё в наименовании присутствует опечатка

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String message) {
параметр в конструкторе есть, но нигде не используется. Зачем он?

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
лучше использовать NotNull из javax.validation.constraints. Ломбок всё равно заменит их, поэтому лучше сразу использовать то, что нужно. (кстати, идея это тоже подсказывает)

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NonNull
Здесь тоже NotNull лучше

2023-07-06 10:43 UTC, mysosnovskaya commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=TRACE
Обычно уровень ставят INFO, а уровни ниже (debug, trace) ставят только при необходимости. Например, если происходит какая-то ошибка и её нужно продебажить с помощью логов

2023-07-06 10:43 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    public void createUserWithUncorrectData() {
incorrect вместо uncorrect

2023-07-07 06:08 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String message) {
Я создаю новое исключение throw new ValidationException и передаю ему сообщение об ошибке. После я добавил try-catch, поймал это исключение и вывел текст ошибки.
Только я не понимаю, что я должен вернуть, когда дата не соответствует требованиям и возникает ошибка?

`@PostMapping
    public Film addFilm(@Valid @RequestBody Film film) {
        try {
            if (film.getReleaseDate().isAfter(CONTROL_RELEASE_DATE)) {
                film.setId(generatedId++);
                films.put(film.getId(), film);
            } else {
                throw new ValidationException("Фильм не добавлен, дата релиза должна быть не раньше "
                        + CONTROL_RELEASE_DATE);
            }
        } catch (ValidationException e) {
            System.out.println(e.getMessage());
        }
        return film;
    }`

2023-07-07 06:11 UTC, PrincSiama commented
Осталось разобраться с обработкой собственного исключения. 
и еще, не понятно, нужно делать новый коммит и загружать сейчас новый наполовину откорректированный код?

2023-07-07 10:43 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String message) {
Да, ты в конструктор передаешь сообщение об ошибке, а дальше оно теряется, т.к. никуда не передается (никакому полю переданное значение не присваивается).

catch не нужно делать, как раз исключение и должно вернуться. Будет ошибка со статус кодом 500, постман тесты как раз это и ожидают

2023-07-07 10:45 UTC, mysosnovskaya commented
> Осталось разобраться с обработкой собственного исключения. и еще, не понятно, нужно делать новый коммит и загружать сейчас новый наполовину откорректированный код?

Если хочешь, чтобы я посмотрела эту половину изменений, то отправляй коммит. Если нет, то сначала всё исправь, потом делай коммит)

2023-07-08 15:55 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate controlReliseDate = LocalDate.of(1895, 12, 28);
сделал private final static LocalDate CONTROL_RELEASE_DATE. Проверка ругается на поле static.

2023-07-08 19:42 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate controlReliseDate = LocalDate.of(1895, 12, 28);
Ладно, значит она не принимает константы. Пусть тогда остается так, как у тебя сейчас)

2023-07-08 19:42 UTC, mysosnovskaya approved these changes

2023-07-09 01:57 UTC, merged