Add database
PrincSiama/java-filmorate pull request #5
Opened 2023-08-17 16:23 UTC by PrincSiama

2023-08-17 16:48 UTC, PrincSiama reviewed
удалена пустая строка в классе User

2023-08-19 12:54 UTC, mysosnovskaya requested changes

2023-08-19 12:54 UTC, mysosnovskaya commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jdbc</artifactId>
Похоже, что эта зависимость не нужна, т.к. есть spring-boot-starter-jdbc

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @RequestBody Film film) throws SQLException {
Исключения лучше не тащить до контроллеров. Обычно их отлавливают там, где они могут возникнуть (в твоем случае это в storage-классах) и оборачивают в непроверяемое исключение (можно создать собственное SqlException). А затем это исключение отлавливают в ErrorHandler.

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, Integer duration) {
А зачем этот и следующие конструкторы, если они нигде не используются?

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private final String email;
А почему ты final везде удалил? Из-за row mapper? Точно ли никак нельзя оставить final?

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +@Primary
Это хорошо! Правильное использование в правильном месте

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/resources/schema.sql
> +ALTER TABLE films ADD CONSTRAINT films_fk FOREIGN KEY (rating_id) REFERENCES ratings(rating_id) ON DELETE CASCADE ON UPDATE SET DEFAULT;
На будущее: обычно все внешние ключи прописывают сразу при создании таблицы таким образом:
rating_id int4 NOT NULL references ratings(rating_id),
Я знаю, что так сгенерировал dbeaver, так что можешь оставить.

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +                if (rs.getRow() == 1) {
А нельзя это вынести перед циклом? Чтобы на каждой итерации не делать эту проверку, которая точно срабатывает только один раз в самом начале и больше никогда

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "select rating_id from ratings";
Через count проще

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +    public boolean isExistMpa(Integer id) {
А может быть методы, относящиеся к mpa, вынести в отдельный класс MpaDbStorage? Будет легче ориентироваться. Возможно, ещё какие-то методы можно так же вынести в отдельные классы?

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDbStorage.java
> +        String sqlRequest = "select user_id from users order by user_id";
Через count

2023-08-19 12:54 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDbStorage.java
> +        return false;
Это почему?

2023-08-21 08:36 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, Integer duration) {
Конструкторы удалены

2023-08-21 08:37 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public int compareTo(Genre g) {
Форматирование поправлено

2023-08-21 08:48 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private final String email;
В row mapper нам необходимо установить id, email, login, name, birthday и friends через сеттеры, с final полями не получится этого сделать

2023-08-21 11:30 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        Connection connection = jdbcTemplate.getDataSource().getConnection();
Переделал с использованием jdbcTemplate.batchUpdate()

2023-08-21 11:35 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequestGenre = "merge into films_genres (film_id, genre_id) values (?, ?)";
Сделал, работает с insert into

2023-08-21 11:35 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +            for (Genre genre : genres) {
Переделал с использованием jdbcTemplate.batchUpdate()

2023-08-21 15:38 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "select film_id from films order by film_id";
Откорректировал

2023-08-21 15:53 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "select rating_id from ratings";
откорректировано

2023-08-21 15:54 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDbStorage.java
> +        String sqlRequest = "INSERT INTO friends (user_id, friend_id) VALUES (?, ?)";
откорректировано

2023-08-21 15:59 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDbStorage.java
> +        return false;
Этот метод не используется, удален

2023-08-21 16:00 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDbStorage.java
> +        String sqlRequest = "select user_id from users order by user_id";
откорректировано

2023-08-22 10:19 UTC, PrincSiama commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jdbc</artifactId>
Удалена

2023-08-22 10:20 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +                if (rs.getRow() == 1) {
Вроде получилось

2023-08-22 10:22 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +                        Film film2 = new Film();
Откорректировано

2023-08-22 10:24 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "insert into likes (film_id, user_id) values (?,?)";
Лайки хранятся в множестве, поэтому лишний лайк не добавится. Не знаю, стоит ли писать проверку?

2023-08-22 10:30 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @RequestBody Film film) throws SQLException {
С использованием dbcTemplate.batchUpdate исключение вроде обрабатывается в методе setValues и дальше не тащится

2023-08-22 13:38 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +    public boolean isExistMpa(Integer id) {
Вынес методы mpa в класс MpaDbStorage, методы genre в класс GenreDbStorage

2023-08-25 20:07 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private final String email;
А почему именно через сеттер? Можно же и через конструктор сделать. В методе пишем return new User(rs.getInteger("id"), ....);

2023-08-25 20:07 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "insert into likes (film_id, user_id) values (?,?)";
Это они в коде в джаве хранятся в множестве и дублирования не будет. А в базе данных? Могут ли быть в таблице повторяющиеся лайки? Если да, то это лишняя информация. Память занимает, а пользы никакой, и в таком случае нужно подумать, как не допустить дублирования в базе данных

2023-08-25 20:07 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
Да, так хорошо. А можно это же сделать с помощью лямбды?

2023-08-26 12:46 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "insert into likes (film_id, user_id) values (?,?)";
В базе данных повторяющиеся значения исключены, я проверил: для одного и того же фильма один и тот же пользователь не может поставить два лайка.

![image](https://github.com/PrincSiama/java-filmorate/assets/125671106/0f04f54c-bdb0-4366-bd74-8b9eb60988d4)

2023-08-26 13:07 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private final String email;
Можно. Сделал через конструктор. Только id все равно нужно будет оставить не final, т.к. когда мы получаем id из базы мы должны установить его уже существующему юзеру или фильму.

2023-08-26 13:45 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
Подозреваю, что можно. Но мне что-то никакое рабочее решение в голову не пришло. И вообще, даже не очень понимаю с какого места лямбду начинать :(

2023-08-26 13:49 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
Подозреваю, что можно. Но мне что-то никакое рабочее решение в голову не пришло. И вообще, даже не очень понимаю с какого места лямбду начинать :(

2023-08-26 16:11 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> -    private final String email;
Сделал через конструктор. Только id пришлось оставить не final, потому что мы устанавливаем полученный из БД id фильма и пользователя.

2023-08-26 16:47 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
вот что у меня получилось

`jdbcTemplate.batchUpdate(sqlRequestGenre, genres, 100,
                (PreparedStatement ps, Genre genre) -> {
                    ps.setInt(1, film.getId());
                    ps.setInt(2, genre.getId());
                });`

2023-08-27 15:18 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
Хорошо, а откуда 100 взялось третьим параметром? Почему именно 100?

2023-08-27 15:19 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        String sqlRequest = "insert into likes (film_id, user_id) values (?,?)";
Хорошо, это правильно

2023-08-28 07:00 UTC, PrincSiama commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDbStorage.java
> +        int[] updateCounts = jdbcTemplate.batchUpdate(sqlRequest, new BatchPreparedStatementSetter() {
Если я правильно понял, то это максимальный размер записей в batchUpdate, который может там накапливаться, после чего будет передан в БД. 
Вместо 100 там должно быть genres.size().

2023-08-31 05:01 UTC, merged